### ISSUE TITLE
Step 4 compilation generate DataSource, but gives a compilation error saying DataSource not found.

### ISSUE THREAD

**Issue by madukan** [Dhi13man/spring-multi-data-source#19]
**Describe the bug**
I get an error "No config found for data sources: [ds1, replica]. Please provide a @DataSourceConfig for each data source in the @EnableMultiDataSourceConfig annotation."

**To Reproduce**
I am at the https://github.com/Dhi13man/spring-multi-data-source Step 4.

**Expected behavior**
It should compile and generate the expected sources.

**Screenshots**
<img width="1095" alt="image" src="https://github.com/Dhi13man/spring-multi-data-source/assets/7971561/0e92b927-7682-4e52-8739-7a6b80c01cf6">

**Desktop (please complete the following information):**

- OS: macOS
- Java 21
```
 java -version
java version "21.0.1" 2023-10-17
Java(TM) SE Runtime Environment Oracle GraalVM 21.0.1+12.1 (build 21.0.1+12-jvmci-23.1-b19)
Java HotSpot(TM) 64-Bit Server VM Oracle GraalVM 21.0.1+12.1 (build 21.0.1+12-jvmci-23.1-b19, mixed mode, sharing)
```

**Comment by madukan** [comment]
Demo repository created:
https://github.com/madukan/MultiDbSpringDataJPA4

**Comment by DhimanSeal-Groww** [comment]
Hey @madukan. A couple of things here.

1. This library was designed with the assumption that your primary data source would be able to access every repository in your project, other than the generated repositories. Repositories would only be generated for your secondary data sources. You do not need to specially mark your repository methods with `@TargetDataSource("<primary_data_source_name>")` as all non-generated repository methods will be accessible by the primary data source. However, if you have a specific requirement to do this, we can discuss it further.

2. The way to work with multiple data sources in Spring boot is by segregating the repositories of each data source into separate packages/folders. This library was made to generate this segregation automatically. I can see in your demo repository that you already have your packages segregated by data source. In that case, you might not have any need for this library as you have already done half the work that this library would have done. The only other thing this library would do is to generate the configuration beans for you.

**Comment by Dhi13man** [comment]
Hey @madukan. Thanks for your time in exploring this project. A couple of things here.

1. This library was designed with the assumption that your primary data source would be able to access every repository in your project, other than the generated repositories. Repositories would only be generated for your secondary data sources. You do not need to specially mark your repository methods with `@TargetDataSource("<primary_data_source_name>")` as all non-generated repository methods will be accessible by the primary data source. However, if you have a specific requirement to do this, we can discuss it further.

2. The way to work with multiple data sources in Spring boot is by segregating the repositories of each data source into separate packages/folders. This library was made to generate this segregation automatically. I can see in your demo repository that you already have your packages segregated by data source. In that case, you might not have any need for this library as you have already done half the work that this library would have done. The only other thing this library would do is to generate the configuration beans for you.

**Comment by madukan** [comment]
Hi @Dhi13man, thank you for your prompt response. And I must also say this project is a great effort in a problematic area in Spring Data!

With regards to the second point you mentioned. The `@EnableMultiDataSourceConfig` uses only packages to refer to the repositories and entities, right? So does that mean this framework would create Configurations for all the repositories to access all the data sources?

ie, my `EnableMultiDataSourceConfig` looks like this:

```java

import io.github.dhi13man.spring.datasource.annotations.EnableMultiDataSourceConfig;
import org.springframework.context.annotation.Configuration;

@Configuration
@EnableMultiDataSourceConfig(
        repositoryPackages = {
                "com.example.multidbspringdatajpa4.db1.repo",
                "com.example.multidbspringdatajpa4.db2.repo"
        },
        exactEntityPackages = {
                "com.example.multidbspringdatajpa4.db1.entities",
                "com.example.multidbspringdatajpa4.db2.entities"
        },
        dataSourceConfigs = {
                @EnableMultiDataSourceConfig.DataSourceConfig(dataSourceName = "ds1", isPrimary = true),
                @EnableMultiDataSourceConfig.DataSourceConfig(dataSourceName = "ds2")
        }
)
public class ServiceConfig1 {

}
```


For your point one, have you got a full example somewhere?

**Comment by Dhi13man** [comment]
Hey @madukan. I have made a few changes for easier understanding.

1. Split the `@EnableMultiDataSourceConfig` annotation configuration to segregate Primary and Secondary datasources better. The primary datasource can access all repositories (except generated repository classes) and secondary datasources can only access their respective generated repository classes. I raised a full PR of changes here and I would love your feedback: https://github.com/Dhi13man/spring-multi-data-source/pull/21

2. I raised a PR in your demo project to integrate the same, and fix some other minor issues. Everything is working fine now. Please test: https://github.com/madukan/MultiDbSpringDataJPA4/pull/1

**Comment by Dhi13man** [comment]
Merged this PR with a lot more improvements too, including the possibility of adding different JPA Properties to different Data Sources. Hoping the new config and documentation will help better illustrate the idea behind the set up. Thank you once again for the feedback.
